game/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from game import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("src.urls", namespace="src")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/urls.py
from django.urls import path

from src.views import ShowUploadPage, ShowMainPage

app_name = "src"

urlpatterns = [
    path("", ShowUploadPage.as_view(), name="upload"),
    path("main/", ShowMainPage.as_view(), name="main"),

]

src/models.py
from django.db import models

# Create your models here.

src/views.py
from django.views.generic import TemplateView

class ShowUploadPage(TemplateView):
    template_name = "src/upload.html"

class ShowMainPage(TemplateView):
    template_name = "src/index.html"
    

src/templates/src/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<canvas id="matrix-canvas"></canvas>

{% comment %} <div class="center-container">
    <div class="terminal">
        <span id="typed-text"></span>
    </div>
    
    <a href={% url 'src:main' %} id="join-button" class="join-button" target="_blank" rel="noopener noreferrer">Присоединиться</a>
</div>

<div class="micro-signal">
    <span class="dot-micro"></span>
    <span>······</span>
</div> {% endcomment %}
{% endblock %}

src/templates/src/upload.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<canvas id="matrix-canvas"></canvas>

<div class="center-container">
    <div class="terminal">
        <span id="typed-text"></span>
    </div>
    
    <a href={% url 'src:main' %} id="join-button" class="join-button" target="_blank" rel="noopener noreferrer">Присоединиться</a>
</div>

<div class="micro-signal">
    <span class="dot-micro"></span>
    <span>······</span>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link type="text/css" href="{% static 'src/css/styles.css' %}" rel="stylesheet"/>
    <link rel="shortcut icon" href="{% static 'src/images/favicon.ico' %}">
    
    <!-- Подключаем CSS для страницы матрицы -->
    <link type="text/css" href="{% static 'src/css/matrix.css' %}" rel="stylesheet"/>
    
    <title>РЭА Минэнерго / virtual universe</title>
</head>
<body>
    
    {% comment %} {% include 'header.html' %} {% endcomment %}

    {% block content %}
    {% endblock content %}

    {% comment %} {% include 'footer.html' %} {% endcomment %}

    <!-- JS local -->
    <script src="{% static 'src/js/script.js' %}"></script>
    <!-- Подключаем JS для страницы матрицы -->
    <script src="{% static 'src/js/matrix.js' %}"></script>
    
</body>
</html>